[package]
name = "kite-server"
version = "0.1.0"
authors = ["sunnysab <sunnysab@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1"

r2d2 = "0.8"
r2d2-diesel = "1.0.0"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

diesel = { version = "1.4.3", features = ["postgres"] }